const CSS = [
  '.pbb-section{max-width:760px;color:var(--dsw-alias-label-primary);display:flex;flex-direction:column;gap:10px}',
  '.pbb-pageHeader{display:flex;align-items:flex-start;gap:16px;padding:2px 2px 4px}',
  '.pbb-title{margin:0;font-size:18px;font-weight:600;letter-spacing:-.01em}',
  '.pbb-intro{color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:1.5;margin:4px 0 0;max-width:560px}',
  '.pbb-refresh{font:inherit;font-size:12px;color:var(--dsw-alias-label-secondary);cursor:pointer;background:none;border:none;padding:3px 0;margin-left:auto;white-space:nowrap}',
  '.pbb-refresh:hover:not(:disabled){color:var(--dsw-alias-label-primary)}',
  '.pbb-refresh:disabled{cursor:default;opacity:.5}',
  '.pbb-card{border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-3);border-radius:12px;overflow:hidden}',
  '.pbb-cardHeader{display:flex;align-items:flex-start;gap:16px;padding:15px 18px 13px}',
  '.pbb-cardHeader>div:first-child{min-width:0;flex:1}',
  '.pbb-cardTitle{margin:0;font-size:13px;font-weight:600;color:var(--dsw-alias-label-primary)}',
  '.pbb-cardDescription{margin:3px 0 0;color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:1.45}',
  '.pbb-cardBody,.pbb-pairingBody{display:flex;flex-direction:column;gap:10px;padding:0 18px 15px}',
  '.pbb-sectionIntro{padding-bottom:2px}',
  '.pbb-row{display:flex;align-items:center;gap:8px}',
  '.pbb-label{flex:1;font-size:12px;font-weight:500;color:var(--dsw-alias-label-primary);min-width:0}',
  '.pbb-value{font-size:12px;color:var(--dsw-alias-label-secondary);word-break:break-all;text-align:right}',
  '.pbb-badge,.pbb-countBadge{background:var(--dsw-alias-bg-module-platform);color:var(--dsw-alias-label-secondary);border-radius:999px;padding:2px 8px;font-size:11px;font-weight:500;white-space:nowrap}',
  '.pbb-countBadge{min-width:24px;text-align:center}',
  '.pbb-statusBadge{display:inline-flex;align-items:center;gap:6px;flex:none;padding:3px 8px;border-radius:999px;background:var(--dsw-alias-bg-module-platform);color:var(--dsw-alias-label-secondary);font-size:11px;font-weight:500;white-space:nowrap}',
  '.pbb-ok{color:var(--dsw-alias-state-success-primary,var(--dsw-alias-label-secondary));font-weight:500}',
  '.pbb-bad{color:var(--dsw-alias-label-error);font-weight:500}',
  '.pbb-diag{font-size:11px;color:var(--dsw-alias-label-tertiary);margin:0;line-height:1.5;overflow-wrap:anywhere}',
  '.pbb-diagBad{color:var(--dsw-alias-label-error)}',
  '.pbb-empty{color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:1.55;margin:0;padding:12px;border:1px dashed var(--dsw-alias-border-l2);border-radius:8px}',
  '.pbb-tokenRow{flex-wrap:wrap}',
  '.pbb-token{max-width:100%;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:var(--dsw-alias-label-secondary);word-break:break-all}',
  '.pbb-tokenActions{display:flex;align-items:center;gap:8px}',
  '.pbb-action{font:inherit;font-size:12px;color:var(--dsw-alias-label-secondary);cursor:pointer;background:none;border:1px solid var(--dsw-alias-border-l2);border-radius:7px;padding:5px 9px;line-height:1.2;white-space:nowrap}',
  '.pbb-action:hover:not(:disabled){color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-module-platform)}',
  '.pbb-action:disabled{cursor:default;opacity:.5}',
  '.pbb-buttonPrimary{color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-state-success-primary,#3b82f6);background:color-mix(in srgb,var(--dsw-alias-state-success-primary,#3b82f6) 12%,transparent)}',
  '.pbb-buttonPrimary:hover:not(:disabled){color:var(--dsw-alias-label-primary);background:color-mix(in srgb,var(--dsw-alias-state-success-primary,#3b82f6) 18%,transparent)}',
  '.pbb-actionSelected{color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-state-success-primary,#22a06b);background:var(--dsw-alias-bg-module-platform)}',
  '.pbb-actionDangerGhost{color:#dc2626;border-color:rgba(220,38,38,.38);background:transparent;line-height:1.35;padding:4px 9px;transition:color .15s ease,background-color .15s ease,border-color .15s ease,transform .1s ease}',
  '.pbb-actionDangerGhost:hover:not(:disabled){color:#b91c1c;background:rgba(220,38,38,.09);border-color:rgba(185,28,28,.5)}',
  '.pbb-actionDangerGhost:active:not(:disabled){transform:translateY(1px)}',
  '.pbb-actionDangerGhost:focus-visible{outline:2px solid rgba(220,38,38,.32);outline-offset:1px}',
  '.pbb-actionDangerGhost:disabled{cursor:default;opacity:.62}',
  '.pbb-actionIcon{flex:none;display:inline-block;vertical-align:-2px;margin-right:5px;pointer-events:none}',
  '.pbb-actionBusy{display:inline-flex;align-items:center;gap:6px}',
  '.pbb-actionBusy::before{content:"";width:9px;height:9px;border-radius:50%;border:1.5px solid rgba(220,38,38,.35);border-top-color:currentColor;animation:pbb-spin .7s linear infinite}',
  '@keyframes pbb-spin{to{transform:rotate(360deg)}}',
  '.pbb-masterRow{display:flex;align-items:center;gap:14px;padding:0 18px 14px}',
  '.pbb-switchText{display:flex;flex-direction:column;gap:3px;flex:1;min-width:0}',
  '.pbb-switchTitle{font-size:13px;font-weight:500;color:var(--dsw-alias-label-primary)}',
  '.pbb-switchDesc{font-size:11px;color:var(--dsw-alias-label-tertiary);line-height:1.4}',
  '.pbb-switch{appearance:none;-webkit-appearance:none;width:34px;height:20px;border-radius:999px;background:var(--dsw-alias-bg-module-platform);border:1px solid var(--dsw-alias-border-l2);position:relative;cursor:pointer;padding:0;flex:none;transition:background .15s ease,border-color .15s ease}',
  '.pbb-switch::after{content:"";position:absolute;top:2px;left:2px;width:14px;height:14px;border-radius:50%;background:var(--dsw-alias-label-secondary);transition:transform .15s ease,background .15s ease}',
  '.pbb-switchOn{background:var(--dsw-alias-state-success-primary,#22a06b);border-color:transparent}',
  '.pbb-switchOn::after{transform:translateX(14px);background:#fff}',
  '.pbb-switch:disabled{opacity:.5;cursor:default}',
  '.pbb-switch:focus-visible,.pbb-action:focus-visible,.pbb-targetButton:focus-visible{outline:2px solid color-mix(in srgb,var(--dsw-alias-state-success-primary,#3b82f6) 55%,transparent);outline-offset:2px}',
  '.pbb-connectionGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;padding:0 18px 14px}',
  '.pbb-connectionTile{min-width:0;border:1px solid var(--dsw-alias-border-l2);border-radius:9px;background:var(--dsw-alias-bg-module-platform);padding:11px 12px;display:flex;flex-direction:column;gap:5px}',
  '.pbb-connectionTileHeader{display:flex;align-items:center;gap:10px}',
  '.pbb-dotRow{display:flex;align-items:center;gap:7px;flex:1;min-width:0}',
  '.pbb-dot{width:7px;height:7px;border-radius:50%;background:var(--dsw-alias-label-tertiary);flex:none}',
  '.pbb-dotOk{background:var(--dsw-alias-state-success-primary,#22a06b)}',
  '.pbb-dotWarn{background:var(--dsw-alias-state-warning-primary,#e2b203)}',
  '.pbb-dotBad{background:var(--dsw-alias-label-error)}',
  '.pbb-connectionState{font-size:11px;color:var(--dsw-alias-label-secondary);font-weight:500}',
  '.pbb-connectionDescription{font-size:11px;color:var(--dsw-alias-label-tertiary);line-height:1.45;margin:0}',
  '.pbb-rowAction{display:flex;gap:8px;margin-top:4px}',
  '.pbb-statGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:0 18px 14px}',
  '.pbb-stat{display:flex;align-items:center;gap:8px;min-width:0;padding:8px 10px;border-radius:8px;background:var(--dsw-alias-bg-module-platform)}',
  '.pbb-statLabel{font-size:11px;color:var(--dsw-alias-label-tertiary);flex:1}',
  '.pbb-statValue{font-size:12px;color:var(--dsw-alias-label-primary);font-weight:600}',
  '.pbb-inlineDetails,.pbb-help{border-top:1px solid var(--dsw-alias-border-l2)}',
  '.pbb-inlineDetails>summary,.pbb-help>summary{cursor:pointer;color:var(--dsw-alias-label-primary);font-size:12px;font-weight:500;user-select:none;list-style:none;display:flex;align-items:center;padding:12px 18px}',
  '.pbb-inlineDetails>summary::-webkit-details-marker,.pbb-help>summary::-webkit-details-marker{display:none}',
  '.pbb-inlineDetails>summary::after,.pbb-help>summary::after{content:"›";margin-left:auto;color:var(--dsw-alias-label-tertiary);font-size:16px;line-height:1;transform:rotate(90deg);transition:transform .15s ease}',
  '.pbb-inlineDetails[open]>summary::after,.pbb-help[open]>summary::after{transform:rotate(-90deg)}',
  '.pbb-inlineDetails[open]>summary,.pbb-help[open]>summary{color:var(--dsw-alias-label-secondary)}',
  '.pbb-helpBody{display:flex;flex-direction:column;gap:14px;padding:2px 18px 15px}',
  '.pbb-helpSection{display:flex;flex-direction:column;gap:6px}',
  '.pbb-helpHeading{font-size:12px;font-weight:600;color:var(--dsw-alias-label-primary)}',
  '.pbb-helpList{margin:0;padding-left:20px;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:1.6}',
  '.pbb-helpList li+li{margin-top:4px}',
  '.pbb-helpText{margin:0;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:1.6}',
  '.pbb-helpCode{display:block;margin:2px 0 0;padding:10px;overflow:auto;white-space:pre-wrap;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-module-platform);color:var(--dsw-alias-label-primary);font:11px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}',
  '.pbb-helpLink{color:var(--dsw-alias-label-secondary);text-decoration:underline;text-underline-offset:2px}',
  '.pbb-limitRow{display:flex;align-items:center;gap:12px;padding:10px 0;border-top:1px solid var(--dsw-alias-border-l2)}',
  '.pbb-limitRow:first-child{border-top:0;padding-top:2px}',
  '.pbb-limitControl{display:flex;align-items:center;gap:8px;flex:none}',
  '.pbb-numberInput{width:72px;box-sizing:border-box;border:1px solid var(--dsw-alias-border-l2);border-radius:7px;background:var(--dsw-alias-bg-layer-3);color:var(--dsw-alias-label-primary);font:inherit;font-size:12px;padding:5px 8px}',
  '.pbb-numberInput:focus{outline:2px solid var(--dsw-alias-state-success-primary,#22a06b);outline-offset:1px}',
  '.pbb-numberInput:disabled{opacity:.5}',
  '.pbb-targetList{display:flex;flex-wrap:wrap;gap:6px}',
  '.pbb-targetButton{font:inherit;font-size:11px;color:var(--dsw-alias-label-secondary);cursor:pointer;background:none;border:1px solid var(--dsw-alias-border-l2);border-radius:7px;padding:6px 9px;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.pbb-targetButton:hover:not(:disabled){color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-module-platform)}',
  '.pbb-targetButton:disabled{cursor:default;opacity:.5}',
  '.pbb-targetSelected{color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-state-success-primary,#22a06b);background:color-mix(in srgb,var(--dsw-alias-state-success-primary,#22a06b) 10%,transparent)}',
  '.pbb-qrPanel{display:flex;flex-direction:column;align-items:center;gap:9px;padding:14px 0 4px;border-top:1px solid var(--dsw-alias-border-l2)}',
  '.pbb-qrImage{width:224px;height:224px;max-width:100%;background:#fff;border-radius:10px;padding:8px;box-sizing:border-box}',
  '.pbb-pairCodeBlock{width:min(100%,460px);display:flex;flex-direction:column;gap:6px}',
  '.pbb-pairCodeLabel{font-size:11px;color:var(--dsw-alias-label-tertiary);text-align:center}',
  '.pbb-pairCodeRow{display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap}',
  '.pbb-pairCode{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px;line-height:1.4;letter-spacing:.03em;color:var(--dsw-alias-label-primary);word-break:break-all;text-align:center;user-select:all}',
  '.pbb-qrHint{max-width:460px;text-align:center;font-size:11px;line-height:1.5;color:var(--dsw-alias-label-tertiary);margin:0}',
  '.pbb-tableWrap{width:100%;overflow-x:auto}',
  '.pbb-table{width:100%;border-collapse:collapse;font-size:12px;table-layout:fixed}',
  '.pbb-table th{color:var(--dsw-alias-label-tertiary);text-align:left;font-weight:500;padding:7px 8px;border-bottom:1px solid var(--dsw-alias-border-l2)}',
  '.pbb-table td{padding:9px 8px;border-bottom:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary);vertical-align:middle}',
  '.pbb-table tbody tr:last-child td{border-bottom:0}',
  '.pbb-table th:first-child{width:48%}',
  '.pbb-table th:nth-child(2){width:32%}',
  '.pbb-tableActionHead,.pbb-tableActionCell{text-align:right;width:142px!important}',
  '.pbb-tableActionCell{white-space:nowrap}',
  '.pbb-tableActionCell>.pbb-action+.pbb-action{margin-left:5px}',
  '.pbb-deviceNameRow{display:flex;align-items:center;gap:6px;min-width:0}',
  '.pbb-deviceName{display:block;font-weight:500;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.pbb-deviceMeta{display:flex;gap:4px;align-items:center;margin-top:3px;color:var(--dsw-alias-label-tertiary);font-size:10px;min-width:0}',
  '.pbb-deviceMeta code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.pbb-deviceRenameForm{display:flex;flex-direction:column;gap:5px;min-width:0}',
  '.pbb-deviceRenameControls{display:flex;align-items:center;gap:7px;min-width:0}',
  '.pbb-deviceRenameControls>.pbb-deviceNameInput{flex:1;width:auto;min-width:0}',
  '.pbb-deviceNameInput{width:100%;box-sizing:border-box;border:1px solid var(--dsw-alias-border-l2);border-radius:7px;background:var(--dsw-alias-bg-layer-3);color:var(--dsw-alias-label-primary);font:inherit;font-size:12px;padding:6px 8px}',
  '.pbb-deviceNameInput:focus{outline:2px solid var(--dsw-alias-state-success-primary,#22a06b);outline-offset:1px}',
  '.pbb-deviceNameInput:disabled{opacity:.5}',
  '.pbb-deviceRenameActions{display:flex;align-items:center;gap:5px;flex:none}',
  '.pbb-deviceIconAction{width:30px;height:30px;display:inline-flex;align-items:center;justify-content:center;padding:0;border-radius:8px;box-shadow:none}',
  '.pbb-deviceRenameActions .pbb-buttonPrimary{color:#fff;border-color:transparent;background:var(--dsw-alias-state-success-primary,#3b82f6)}',
  '.pbb-deviceRenameActions .pbb-buttonPrimary:hover:not(:disabled){color:#fff;background:color-mix(in srgb,var(--dsw-alias-state-success-primary,#3b82f6) 86%,#000)}',
  '.pbb-deviceRenameActions .pbb-deviceIconAction:not(.pbb-buttonPrimary){background:var(--dsw-alias-bg-module-platform);border-color:transparent;color:var(--dsw-alias-label-secondary)}',
  '.pbb-deviceRenameActions .pbb-deviceIconAction:not(.pbb-buttonPrimary):hover:not(:disabled){background:var(--dsw-alias-bg-layer-2,var(--dsw-alias-bg-module-platform));color:var(--dsw-alias-label-primary)}',
  '.pbb-controlIcon{display:block;pointer-events:none}',
  '.pbb-inlineSpinner{width:12px;height:12px;box-sizing:border-box;border:1.5px solid currentColor;border-right-color:transparent;border-radius:50%;animation:pbb-spin .7s linear infinite}',
  '.pbb-lastSeen{color:var(--dsw-alias-label-secondary);font-size:11px;overflow-wrap:anywhere}',
  '.pbb-disclosure{padding:0}',
  '.pbb-disclosure>summary{list-style:none;display:flex;align-items:center;gap:12px;padding:13px 18px;cursor:pointer;color:var(--dsw-alias-label-primary)}',
  '.pbb-disclosure>summary::-webkit-details-marker{display:none}',
  '.pbb-disclosure>summary::after{content:"›";color:var(--dsw-alias-label-tertiary);font-size:17px;line-height:1;transform:rotate(90deg);transition:transform .15s ease}',
  '.pbb-disclosure[open]>summary::after{transform:rotate(-90deg)}',
  '.pbb-disclosureTitle{font-size:12px;font-weight:500;flex:1}',
  '.pbb-disclosureMeta{font-size:11px;color:var(--dsw-alias-label-tertiary);max-width:46%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.pbb-disclosureBody{display:flex;flex-direction:column;gap:12px;padding:2px 18px 16px}',
  '.pbb-testGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}',
  '.pbb-testItem{display:flex;align-items:center;gap:12px;padding:11px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-module-platform)}',
  '.pbb-testTitle{font-size:12px;font-weight:500;color:var(--dsw-alias-label-primary)}',
  '.pbb-testDescription{font-size:10px;color:var(--dsw-alias-label-tertiary);line-height:1.45}',
  '.pbb-runtimeList{display:flex;flex-direction:column;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;overflow:hidden}',
  '.pbb-runtimeList>.pbb-runtimeRow,.pbb-runtimeRow{display:flex;align-items:center;gap:10px;padding:9px 10px;border-top:1px solid var(--dsw-alias-border-l2)}',
  '.pbb-runtimeList>.pbb-runtimeRow:first-child{border-top:0}',
  '.pbb-runtimeList>.pbb-runtimeRow>.pbb-row{flex:1;min-width:0}',
  '.pbb-updateRow{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-success-primary,#22a06b) 35%,var(--dsw-alias-border-l2));border-radius:8px;color:var(--dsw-alias-label-primary);font-size:12px}',
  '.pbb-diagnostics>summary{color:var(--dsw-alias-label-secondary)}',
  '@media (max-width:620px){.pbb-connectionGrid,.pbb-testGrid{grid-template-columns:1fr}.pbb-cardHeader{align-items:flex-start}.pbb-masterRow{align-items:flex-start}.pbb-lastSeen{display:none}.pbb-table th:nth-child(2){width:1px}.pbb-table th:first-child{width:auto}.pbb-tableActionHead,.pbb-tableActionCell{width:132px!important}.pbb-limitRow{align-items:flex-start;flex-direction:column}.pbb-limitControl{align-self:flex-end}}',
].join('\n')

/**
 * Client bundle id, identical to the `window.__ModuleLoader__.load({ id })`
 * identity emitted by tsdown.config.ts. DSH's module system owns style
 * teardown by package id, so this tag must carry the same value.
 */
const PLUGIN_ID = 'dsh-deeppilot'

/**
 * Claim this plugin's page stylesheet against DSH's style ownership.
 *
 * `ClientModuleSystem` tags untagged `<style>` elements only during factory
 * materialization; this sheet is injected from `apply()`, which runs after
 * that point, so it would never be attributed to us. Stamping `data-plugin`
 * ourselves lets the module system's `removeOwnedStyles(id)` delete the sheet
 * when the plugin is unloaded at runtime — the rc.2 Plugin Manager and client
 * entry reconciler both support live removal, and an
 * orphaned sheet would otherwise keep styling a page we no longer own.
 */
export function injectCss(): void {
  if (typeof document === 'undefined') return
  const id = 'dsh-deeppilot/page.css'
  if (document.querySelector('style[data-plugin-css="' + id + '"]') !== null) return
  const tag = document.createElement('style')
  tag.setAttribute('data-plugin', PLUGIN_ID)
  tag.setAttribute('data-plugin-css', id)
  tag.textContent = CSS
  document.head.appendChild(tag)
}
